services:
  postgres:
    image: postgres:14
    restart: unless-stopped
    environment:
      POSTGRES_USER: stremio
      POSTGRES_PASSWORD: stremio_pass
      POSTGRES_DB: movie_db_dev
    ports:
      - '5434:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U stremio -d movie_db_dev']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db_data:


